### ISSUE TITLE
Read second fairness article

### ISSUE THREAD

**Issue by rporta23** [sds-capstone/2022-09-proj7-women-at-table#12]
Solon Barocas, Moritz Hardt, & Arvind Narayanan (2019). Fairness and Machine Learning.[ Fairmlbook.org.](https://fairmlbook.org/)

**Comment by ajhaller** [comment]
**A Broader View of Discrimination:**

- Machine learning systems don’t operate in a vacuum; they are adopted in societies that already have many types of discrimination intertwined with systems of oppression such as racism.
- A separate way to classify discrimination is as direct or indirect.

**The Persistence and Magnitude of Inequality**

- Formal equality under the law primarily addresses direct discrimination and has relatively little effect on indirect discrimination, whether structural, organizational, or interpersonal.
- Predictive systems tend to preserve structural advantages and disadvantages
- Sociologists have long recognized that stereotypes that are used to justify discrimination may in fact be produced by that discrimination.

**Machine learning and structural discrimination**

- To understand the effect of adopting machine learning, we consider five types of stakeholders: decision subjects, the people who provide the training data, domain experts, machine learning experts, and policy makers. 
- Machine learning as generally implemented today shifts power away from the first three categories. 

**Structural interventions for fair machine learning**

- Structural interventions: changing the way machine learning gets built and deployed. This could take the form of a broad social movement, or other collectives including communities, workers, researchers, and users.
- Redistribution and reallocation are terms that refer to interventions that modify a decision-making process to introduce an explicit preference for one or more groups, usually groups considered to be disadvantaged. 
- Formalization aims to curb judgment and discretion.
- Diversity training and formalization are examples of procedural fairness interventions.

**Comment by rporta23** [comment]
read-- interesting point about considering which stakeholders have power and which do not in the process of algorithm design. It seems like those most impacted by the outcomes are also the ones with the least power in the process.

**Comment by MargaretBassney** [comment]
read

**Comment by alejanmg** [comment]
read
