### ISSUE TITLE
Part B Questions to ask + additional Questions

### ISSUE THREAD

**Issue by MargaretBassney** [sds-capstone/2022-09-proj7-women-at-table#34]
**Questions to ask**
Does the dataset contain data that might be considered sensitive in any way?

(e.g., data that reveals racial or ethnic origins, sexual orientations, religious beliefs, political opinions or union memberships, or locations; financial or health data; biometric or genetic data; forms of government identification, such as social security numbers; criminal history)

**Additional Questions**
If the dataset relates to people, are there applicable limits on the retention of the data associated with the instances (e.g., were individuals in question told that their data would be retained for a fixed period of time and then deleted)?

Does the dataset contain data that, if viewed directly, might be offensive, insulting, threatening, or might otherwise cause anxiety?

Does the dataset contain data that might be considered confidential (e.g., data that is protected by legal privilege or by doctor/patient confidentiality, data that includes the content of individuals’ non-public communications)?
If so, please provide a description.

What mechanisms or procedures were used to collect the data (e.g., hardware apparatus or sensor, manual human curation, software program, software API)?

How were these mechanisms or procedures validated?

Did you collect the data from the individuals in question directly, or obtain it via third parties or other sources (e.g., websites)

Over what timeframe was the data collected? Does this timeframe match the creation timeframe of the data associated with the instances

Is the dataset self-contained, or does it link to or otherwise rely on external resources (e.g., websites, tweets, other datasets)?

**Comment by rporta23** [comment]
Code to review in [Baseline_Model_final.ipynb](https://colab.research.google.com/drive/16lg77xfYXWG7ss6ZocjGIB5iLuk1cDEw?authuser=2#scrollTo=yXdZWOevcoqE) under "Part B: Rebalancing Data" subheading.
