### ISSUE TITLE
Selecting Variables to Visualize (Part A)

### ISSUE THREAD

**Issue by ajhaller** [sds-capstone/2022-09-proj7-women-at-table#5]

**Comment by rporta23** [comment]
* female
* age
* emp_in (respondent in workforce)
* fin2 (has debit card)
* fin11 a-h (reasons for no account)
* fin24 (possibility of coming up with emergency funds)
* fin25 (main source of emergency funds)
* account_fin (has an account at a financial institution)
* educ (education)
* fin48 (has national id)
* economy (countries) (35 total)
* economycode (country code)
