### ISSUE TITLE
Financial Characteristics (Part A)

### ISSUE THREAD

**Issue by ajhaller** [sds-capstone/2022-09-proj7-women-at-table#6]

**Comment by rporta23** [comment]
* fin11 a-h (reasons for no account) - Rose
* fin2 (has debit card) - Margaret
* inc_q (household income) - Margaret

**Comment by rporta23** [comment]
See [SDS410_exploration](https://colab.research.google.com/drive/1d5WHPGN5Q5vCDYMIEHJ8zLO9WQN88hYo?authuser=2) google collab notebook.
